DROP TABLE IF EXISTS inventory;

CREATE TABLE inventory (
    item_id TEXT,
    item_name TEXT,
    borrow_proc TEXT,
    location TEXT,
    qty INTEGER,
    age INTEGER,
    zone_id TEXT,
    zone_name TEXT,
    hall_id TEXT,
    hall_name TEXT,
    length REAL,
    width REAL,
    height REAL,
    weight REAL,
    monthly_sales REAL,
    pick_days_m REAL,
    sales_90d REAL,
    pick_days_90d REAL,
    supplier_id TEXT,
    supplier_name TEXT,
    pm TEXT,
    total_qty INTEGER,
    turn_days_total REAL,
    cubic_feet REAL,
    vol_type TEXT,
    floor TEXT,
    loc_type TEXT,
    big_zone_id TEXT,
    big_zone TEXT,
    loc_cubic_feet REAL,
    loc_health TEXT,
    vol_check TEXT,
    total_cubic_feet REAL,
    auto_type TEXT,
    age_bracket TEXT,
    heavy_rack_check TEXT
);