DROP TABLE IF EXISTS inventory;

CREATE TABLE inventory (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id TEXT,
    item_name TEXT,
    borrow_proc TEXT,
    location TEXT,
    qty REAL,
    age INTEGER,
    zone_id TEXT,
    zone_name TEXT,
    hall_id TEXT,
    hall_name TEXT,
    length REAL,
    width REAL,
    height REAL,
    weight REAL,
    monthly_sales REAL,
    pick_days_m REAL,
    sales_90d REAL,
    pick_days_90d REAL,
    supplier_id TEXT,
    supplier_name TEXT,
    pm TEXT,
    total_qty REAL,
    turn_days_total REAL,
    cubic_feet REAL,
    vol_type TEXT,
    loc_code_3 TEXT,
    loc_code_full TEXT,
    loc_code_5 TEXT,
    floor TEXT,
    floor_zone TEXT,
    loc_type TEXT,
    big_zone_id TEXT,
    big_zone TEXT,
    dim_sum REAL,
    max_dim REAL,
    min_dim REAL,
    loc_cubic_feet REAL,
    loc_health TEXT,
    non_compliant TEXT,
    vol_check TEXT,
    total_cubic_feet REAL,
    auto_type TEXT,
    shelf_level TEXT,
    age_bracket TEXT,
    floor_config TEXT,
    heavy_rack_check TEXT,
    assigned_floor TEXT,
    remark TEXT
);