name = "my-inventory-system"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "inventory-db"
database_id = "130306ea-d7fc-44ff-ae01-b9ca6d83fb60"