declare const _default: import("vue").DefineComponent<{}, {}, {
    isLoggedIn: boolean;
    currentUser: string;
    loginLoading: boolean;
    savingConfig: boolean;
    showUnifiedDrawer: boolean;
    showSearchModal: boolean;
    searchTimer: null;
    searchElapsedSec: number;
    loginForm: {
        username: string;
        password: string;
        rememberMe: boolean;
    };
    currentTab: string;
    logTab: string;
    loading: boolean;
    calcProgress: number;
    progressTimer: null;
    progressColors: {
        color: string;
        percentage: number;
    }[];
    draggedIndex: null;
    hasSearched: boolean;
    searchTime: string;
    summaryGridData: never[];
    summaryVolData: never[];
    areaGridTable: never[];
    areaVolTable: never[];
    summaryStats: {
        total_plan_grid: number;
        total_used_grid: number;
        total_rem_grid: number;
        total_plan_vol: number;
        total_used_vol: number;
        total_health: string;
    };
    showColSettingDialog: boolean;
    showEditRoleDialog: boolean;
    showEditPwdDialog: boolean;
    showEditPermDialog: boolean;
    targetUser: string;
    editRoleForm: {
        target_name: string;
        target_role: string;
    };
    editPasswordForm: {
        new_password: string;
    };
    editPermForm: {
        selected_modules: never[];
    };
    loginTimestamp: null;
    loginTimeStr: string;
    sessionDurationStr: string;
    idleCountdownStr: string;
    lastActiveTimestamp: number;
    clockInterval: null;
    TIMEOUT_MS: number;
    availableModules: {
        key: string;
        name: string;
    }[];
    rawColumnsMaster: string[];
    allAvailableColumns: string[];
    form: {
        search_mode: string;
        batch_ids: string;
        batch_zones: string;
        txt_id: string;
        txt_name: string;
        cbo_big_zone: string;
        cbo_zone: string;
        cbo_loc_id: string;
        cbo_floor: string;
        cbo_type: string;
        cbo_vol_type: string;
        txt_age: string;
        txt_weight: string;
        txt_monthly_sales: string;
        selected_columns: string[];
        chk_show_loc: boolean;
        chk_show_dim: boolean;
        cbo_sort: string;
        sort_order: string;
    };
    options: {
        big_zones: never[];
        zones_map: {};
        zones: never[];
        floors: never[];
        ap_types: never[];
        vol_types: never[];
    };
    summary: {
        total_items: number;
        total_rows: number;
        total_pcs: number;
        total_ao: number;
    };
    columns: never[];
    tableData: never[];
    usersList: never[];
    logsList: never[];
    showAddUserDialog: boolean;
    newUserForm: {
        username: string;
        name: string;
        role: string;
    };
}, {
    isAdmin(): boolean;
    filteredLogsList(): never[];
}, {
    formatNumber(val: any): any;
    handleBatchUsersUpload(event: any): Promise<void>;
    openRoleDialog(row: any): void;
    handleUpdateRole(): Promise<void>;
    exportUsersExcel(): Promise<void>;
    loadColumnConfig(): Promise<void>;
    saveColumnConfig(): Promise<void>;
    formatLoginTimeStr(): void;
    startTimers(): void;
    stopTimers(): void;
    resetUserActivity(): void;
    updateClockTick(): void;
    handleAutoLogout(): Promise<void>;
    getDeviceType(): "📱 手機" | "💻 電腦";
    isErrorAction(action: any): any;
    openSearchModal(): Promise<void>;
    sendLog(feature: any, action: any): Promise<void>;
    getColWidth(colName: any): 110 | 320 | 180 | 90 | 130;
    getColLetter(idx: any): any;
    getColOriginalIndex(colName: any): number;
    getSelectedOrder(colName: any): number | "-";
    toggleColumnSelection(colName: any): void;
    onDragStart(event: any, idx: any): void;
    onDragOver(event: any, idx: any): void;
    onDrop(): void;
    onDragEnd(): void;
    syncSelectedColumnsOrder(): void;
    selectAllCols(): void;
    unselectAllCols(): void;
    openPwdDialog(row: any): void;
    openPermDialog(row: any): void;
    handleUpdatePassword(): Promise<void>;
    handleUpdatePermissions(): Promise<void>;
    startProgressSimulation(): void;
    finishProgressSimulation(): void;
    handleSummaryCalc(): Promise<void>;
    tableRowStyle({ row }: {
        row: any;
    }): "" | "grandtotal-row-dark" | "subtotal-row-dark";
    getHealthClass(val: any): "" | "text-success" | "text-danger" | "text-warning";
    handleSettingsCommand(cmd: any): void;
    fetchUsers(): Promise<void>;
    handleAddUser(): Promise<void>;
    deleteUser(username: any): Promise<void>;
    fetchLogs(): Promise<void>;
    handleLogin(): Promise<void>;
    handleLogout(): void;
    switchTab(tabKey: any): void;
    resetForm(): void;
    getTabName(tabKey: any): any;
    fetchInitData(): Promise<void>;
    onBigZoneChange(val: any): void;
    handleSearch(): Promise<void>;
    exportData(fmt: any): void;
}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
export default _default;
